/**
 * The widget's stylesheet, inside its shadow root: the design tokens of docs/05 §3 (the band
 * colours only ever for bands), the site's font stacks, which fall back to the system's serif,
 * sans and monospace faces on a page that does not load the site's fonts (the widget loads
 * none), 2 px radii, hairlines, no shadow. A test checks that every colour is a token.
 */
export const CSS = [
  ':host{display:block;container-type:inline-size;margin:16px 0;color:#15161a;background:#fff;text-align:start;font:400 16px/1.35 "Source Sans 3 Variable","Source Sans 3 Fallback","Helvetica Neue",Arial,sans-serif}',
  '.w{display:flex;flex-direction:column;gap:12px;padding:16px 0;border-block:1px solid #d6d6d0}',
  'p,ul{margin:0}',
  'a{color:#1d4f91;text-decoration-line:underline;text-decoration-thickness:1px;text-underline-offset:3px}',
  'a:hover{text-decoration-thickness:2px}',
  'a:focus-visible{outline:2px solid #1d4f91;outline-offset:2px}',
  '.nm,.sc0{font-family:"Newsreader Variable",Georgia,"Times New Roman",serif;font-weight:400;line-height:1.05;font-variant-numeric:tabular-nums}',
  '.nm{font-size:28px}',
  '.sc0{font-size:64px}',
  '.row,.hd{display:flex;flex-wrap:wrap;align-items:center;gap:8px 24px}',
  '.row{align-items:baseline;justify-content:space-between}',
  '.i2{color:#4b4d53}',
  '.sb{font-weight:600}',
  '.f14{font-size:14px}',
  '.f12{font-size:12px}',
  '.chip{display:inline-flex;align-items:center;gap:6px;padding:2px 6px;border-radius:2px;font-size:14px;background:color-mix(in srgb,var(--b) 14%,#fff)}',
  '.sw{width:8px;height:8px;background:var(--b)}',
  '.b-sustaining{--b:#7a1f1a}',
  '.b-enabling{--b:#c4613e}',
  '.b-passive{--b:#b9b3a6}',
  '.b-acting{--b:#4f8a88}',
  '.b-confronting{--b:#16504f}',
  'rect[class^="b-"]{fill:var(--b)}',
  '.st{fill-opacity:.06}',
  '.sc{fill:#f3f3f0;stroke:#d6d6d0}',
  '.sp,.sr,.tk,.g0,.i3,.ln{stroke-width:1px}',
  '.sp{stroke:#fff}',
  '.sr{stroke:#d6d6d0}',
  '.tk{stroke:#15161a}',
  '.g0,.i3{stroke:#6f7278}',
  '.ik{fill:#15161a}',
  '.op{fill:#fff;stroke:#15161a;stroke-width:1.5px}',
  '.ln{fill:none;stroke:#15161a;stroke-width:1.5px;vector-effect:non-scaling-stroke}',
  'svg{display:block}',
  'text{font:400 11px "Source Code Pro",Menlo,Consolas,monospace;fill:#4b4d53}',
  '.tl{display:grid;grid-template-columns:40px 1fr}',
  '.bar{display:flex;gap:2px;height:8px;padding:0;list-style:none}',
  '.bar li{flex:1}',
  '.k{background:#15161a}',
  '.h,.u{border:1px solid #d6d6d0}',
  '.h{background:repeating-linear-gradient(45deg,#d6d6d0 0 2px,transparent 2px 6px)}',
  '.cv{display:flex;flex-direction:column;gap:8px}',
  '@container (max-width:480px){.q{display:none}}',
  '@media print{.bar,.sw,.chip{print-color-adjust:exact}}',
].join('')
